#!/bin/bash

set -e

./cleanup
(cd ./source && gcc -std=c99 -pedantic -Wall -Werror -Wextra -c hoof.c)

./cleanup
(cd ./source && gcc -O3 -I . -c hoof.c -o hoof.o)
(cd ./example_client && gcc -O3 -I ../source/ -c example_client.c -o example_client.o)
(cd ./example_client && gcc -O3 example_client.o ../source/hoof.o -o ../hoof)

strip -s ./hoof

stat -c '%s %n' ./hoof

