#!/bin/bash

set -e

./cleanup
(cd ./source && gcc -std=c99 -pedantic -Wall -Werror -Wextra -c hoof.c)

./cleanup
(cd ./source && gcc -Os -I . -c hoof.c -o hoof.o)
(cd ./example_client_2 && gcc -Os -I ../source/ -c example_client_2.c -o example_client_2.o)
(cd ./example_client_2 && gcc -Os example_client_2.o ../source/hoof.o -o ../hoof)

strip -s ./hoof

stat -c '%s %n' ./hoof

