#!/bin/bash

rm -f ./source/*.o
rm -f ./source/*.a
rm -f ./example_client_1/*.o
rm -f ./example_client_2/*.o
rm -f hoof
rm -f ./tests/misc/misc.o
rm -f ./tests/misc/misc
rm -f ./source/*.gcno
rm -f ./source/*.gcda
rm -f ./*.gcov
rm -rf lcov
rm -f outa
rm -f outb
rm -f outread
rm -f outerror
rm -f bad

